### ISSUE TITLE
Zones/accessories might not be correct after inital setup

### ISSUE THREAD

**Issue by oynek** [SeydX/homebridge-tado-thermostat#7] opened 2018-03-26 14:19 UTC
My current tado setup looks like this:

Living room: 1x tado smart radiator thermostat, 1x tado smart wall mounted thermostat
bathroom: 1x tado smart radiator thermostat
bed room: 1x tado smart radiator thermostat

```
[2018-3-26 14:01:05] [Thermostat] Home ID is: XXXX                                                          
[2018-3-26 14:01:05] [Thermostat] Getting Temperature Unit...  
[2018-3-26 14:01:05] [Thermostat] Found new Zone: Wohnzimmer 0 (4 | RU01)                                     
[2018-3-26 14:01:05] [Thermostat] Found new Zone: Wohnzimmer 1 (4 | VA01)                                     
[2018-3-26 14:01:05] [Thermostat] Found new Zone: Schlafzimmer 0 (2 | RU01)                                   
[2018-3-26 14:01:05] [Thermostat] Found new Zone: Schlafzimmer 1 (2 | VA01)                                   
[2018-3-26 14:01:05] [Thermostat] Found new Zone: Badezimmer 0 (3 | RU01)                                     
[2018-3-26 14:01:05] [Thermostat] Found new Zone: Badezimmer 1 (3 | VA01)                                     
[2018-3-26 14:01:05] [Thermostat] Initializing platform accessory 'Wohnzimmer 0'...                           
[2018-3-26 14:01:05] [Thermostat] Initializing platform accessory 'Wohnzimmer 1'...                           
[2018-3-26 14:01:05] [Thermostat] Initializing platform accessory 'Schlafzimmer 0'...                         
[2018-3-26 14:01:05] [Thermostat] Initializing platform accessory 'Schlafzimmer 1'...                         
[2018-3-26 14:01:05] [Thermostat] Initializing platform accessory 'Badezimmer 0'...                           
[2018-3-26 14:01:05] [Thermostat] Initializing platform accessory 'Badezimmer 1'... 
```

In my use case the plugin creates six different homekit accessories (see log). To my understanding this is not correct. As far as i know the wall mounted tado smart thermostat technically controls the heating request for all radiator valves. It collects information about temperature in every room and sends a heating request to the boiler if neccessary. So from a point of software architecture this could be right - but this is not how the offical tado homekit integration works, it just creates four different accessories .

Furthermore I am not sure if the operation mode of my tados is displayed correctly. See my screenshot:

![file](https://user-images.githubusercontent.com/18418496/37911840-67bb3e2c-3111-11e8-9c22-8e19e3cdb17c.jpeg)

**Comment by seydx** [comment] 2018-03-26 17:04
I will add a new option in the next version for excluding unnecessary types to fix this problem

**Comment by seydx** [comment] 2018-03-27 02:03
v3.2.0 is up
to restrict the plugin not to expose more accessory as needed, you can set following option into your config json:

"includeTypes":["VA01", "RU01"]

if nothing setted, both types will be exposed to HomeKit. If you want to expose only i.e. VA01, just remove "RU01" from the array

**Comment by oynek** [comment] 2018-03-27 06:54
Pretty good work, sir. Tado developers should look for that.

**Comment by seydx** [comment] 2018-03-27 07:21
So it works as intended? Then im closing this issue :)

**Closed as completed by seydx** 2018-03-27 07:21 UTC
Labels: enhancement
